### ISSUE TITLE
can't load opencv_java400

### ISSUE THREAD

**Issue by pekeler** [hellonico/origami#26]
Trying out the example on MacOS

```
$ lein run
...
Retrieving opencv/opencv/4.0.0-0/opencv-4.0.0-0.jar from vendredi
Retrieving opencv/opencv-native/4.0.0-1/opencv-native-4.0.0-1.jar from vendredi
Exception in thread "main" java.io.IOException: Couldn't load library library opencv_java400, compiling:(opencv4/core.clj:10:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
...
Caused by: java.io.IOException: Couldn't load library library opencv_java400
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
...
```

Can anything be done to work around this?

**Comment by hellonico** [comment]
Running mojave yes ?

**Comment by hellonico** [comment]
If you have [brew](https://brew.sh/) install installed, could you run the following ?

```
brew install tbb webp libtiff 
```

**Comment by pekeler** [comment]
Yes, 10.14.3.

After that brew install, lein run succeeds. Thanks!

**Comment by hellonico** [comment]
Added some doc. Thanks for finding this out.
