### ISSUE TITLE
libjpeg missing?

### ISSUE THREAD

**Issue by geokon-gh** [hellonico/origami#4]
Following your installation instructions I get the following error at the last step:
```
$lein run 
OpenJDK 64-Bit Server VM warning: You have loaded library /media/gk/USB_DRIVE/Projects/origami-test/target/native/linux/x86_64/libopencv_java331.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /media/gk/USB_DRIVE/Projects/origami-test/target/native/linux/x86_64/libopencv_java331.so: libjpeg.so.8: cannot open shared object file: No such file or directory, compiling:(/tmp/form-init6812121234660478586.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /media/gk/USB_DRIVE/Projects/origami-test/target/native/linux/x86_64/libopencv_java331.so: libjpeg.so.8: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at clojure.lang.RT.loadLibrary(RT.java:495)
        at user$eval5.invokeStatic(form-init6812121234660478586.clj:1)
        at user$eval5.invoke(form-init6812121234660478586.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more

```
I have libjpeg-dev installed. I'm runnong on Debian-testing

I'm just starting with Clojure, so I'm not sure how to diagnose the problem. I don't really understand how it works and why all the resources are downloaded during `lein run` and where the `/src/` folder is

Can this library work if I just have a vanilla app `lein new app my-origami-app` and then I add 
```
:dependencies [
 [org.clojure/clojure "1.8.0"]
 [origami "0.1.10"]]
```
Or do I need this gorilla stuff and whatnot? Sorry if these are basic questions - I'm just getting started and your library looks great :)

**Comment by hellonico** [comment]
Short is answer is yes, you should only be needed a short project.clj like the one below:

```
(defproject origami-simple "0.1.0-SNAPSHOT"
  :injections [
   (clojure.lang.RT/loadLibrary org.opencv.core.Core/NATIVE_LIBRARY_NAME)
  ]
  :description "FIXME: write description"
  :repositories [["vendredi" "https://repository.hellonico.info/repository/hellonico/"]]
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [   [origami "0.1.10"][org.clojure/clojure "1.8.0"]])
```

I just tried again on a fresh linux/debian install, and opencv native was missing some libraries as well.
I'll try to have a closer look!

**Comment by hellonico** [comment]
Could you try to use this project template:
https://github.com/hellonico/origami-simple

And see if that works better ?

**Comment by geokon-gh** [comment]
I cloned the repo and tried to jack into the REPL and it's giving me some other errors now

```
Starting nREPL server via /usr/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
You can run the command ‘cider-jack-in’ with C-c M-j
Starting nREPL server via /usr/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_ml.so.3.3: cannot open shared object file: No such file or directory, compiling:(/tmp/form-init5457062280818047401.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_ml.so.3.3: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at clojure.lang.RT.loadLibrary(RT.java:495)
	at user$eval1662.invokeStatic(form-init5457062280818047401.clj:1)
	at user$eval1662.invoke(form-init5457062280818047401.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed

error in process sentinel: Could not start nREPL server: Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_ml.so.3.3: cannot open shared object file: No such file or directory, compiling:(/tmp/form-init5457062280818047401.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_ml.so.3.3: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at clojure.lang.RT.loadLibrary(RT.java:495)
	at user$eval1662.invokeStatic(form-init5457062280818047401.clj:1)
	at user$eval1662.invoke(form-init5457062280818047401.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed

```
To be clear - I don't need to install OpenCV from my system repo, correct? The instructions make it sound like I don't - though with how non-portable C++ libraries are between distributions I'm a bit surprised it works like that .

I've always been building OpenCV by hand with custom CMake options- so I don't typically keep a system one around. I'm still trying to understand the whole Lein/Maven ecosystem, so sorry I can't diagnose the problem more thoroughly myself. Thanks for trying to help out here :)

**Comment by hellonico** [comment]
Ah great ! I was just testing on Debian Jessie and at least I am also getting the same error. 
Working on a build now.

**Comment by hellonico** [comment]
For reference, I am including the current project.clj 
```

(defproject origami-simple "0.1.0-SNAPSHOT"
  :injections [ (clojure.lang.RT/loadLibrary org.opencv.core.Core/NATIVE_LIBRARY_NAME)]
  :description "FIXME: write description"
  :repositories [["vendredi" "https://repository.hellonico.info/repository/hellonico/"]]
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [   
  	[opencv/opencv-native "3.3.1_3"] 
  	[origami "0.1.10"]
  	[org.clojure/clojure "1.8.0"]])

```

**Comment by geokon-gh** [comment]
I still have essentially the same issue: 

```
Starting nREPL server via /usr/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
You can run the command ‘cider-jack-in’ with C-c M-j
Starting nREPL server via /usr/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_core.so.3.3: cannot open shared object file: No such file or directory, compiling:(/tmp/form-init3811763440914736472.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_core.so.3.3: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at clojure.lang.RT.loadLibrary(RT.java:495)
	at user$eval1662.invokeStatic(form-init3811763440914736472.clj:1)
	at user$eval1662.invoke(form-init3811763440914736472.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed

error in process sentinel: Could not start nREPL server: Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_core.so.3.3: cannot open shared object file: No such file or directory, compiling:(/tmp/form-init3811763440914736472.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /home/gk/TestingArea/origami-simple/target/native/linux/x86_64/libopencv_java331.so: libopencv_core.so.3.3: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at clojure.lang.RT.loadLibrary(RT.java:495)
	at user$eval1662.invokeStatic(form-init3811763440914736472.clj:1)
	at user$eval1662.invoke(form-init3811763440914736472.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Subprocess failed
```
But I am running : Debian testing buster x86_64 Linux 4.13.0-1-amd64

So maybe it's a different glibc version or some issue like that. Maybe it'd be easier in the longer term to setup Maven/Lein  to just build OpenCV through CMake? It'd be a slower to build everything - but it'd be a bit more fool proof

**Comment by hellonico** [comment]
I just realized I compiled the .so with the wrong flags ... :'(

**Comment by geokon-gh** [comment]
Haha, CMake flags are a mess. Especially the hundred or so OpenCV uses :)

**Comment by geokon-gh** [comment]
Well there is no rush on my end - just fyi. I appreciate you trying to fix it. If you need any CMake help, let me know

**Comment by hellonico** [comment]
Hopefully compiled properly now ... 

I am including the current project.clj from (yet again updated, version 4 of opencv-native-3.3.1) origami-simple:

```

(defproject origami-simple "0.1.0-SNAPSHOT"
  :injections [ (clojure.lang.RT/loadLibrary org.opencv.core.Core/NATIVE_LIBRARY_NAME)]
  :description "FIXME: write description"
  :repositories [["vendredi" "https://repository.hellonico.info/repository/hellonico/"]]
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [   
  	[opencv/opencv-native "3.3.1_4"] 
  	[origami "0.1.10"]
  	[org.clojure/clojure "1.8.0"]])
```

And

```
lein clean 
lein test
```

Hopefully that works for you too !
I tested on Debian and Manjaro. 
Let me know.

**Comment by geokon-gh** [comment]
Just tested and everything is working now :)
Got the sample cat-in-a-bowl running in the REPL

**Comment by hellonico** [comment]
Fantastic. Thank you for standing up through all this.

**Comment by geokon-gh** [comment]
The pleasure it mine. thanks for making the library and helping me use it :)

**Comment by hellonico** [comment]
Released and updated the core packages:

origami
0.1.11-1-g6c4aa45
jvm-opencv
0.0.11-1-ga46fe53
clj-opencv
0.0.11-1-g6ddf7cd
origami-fun
0.1.11

Also, added the debian box settings I used to test here:
https://github.com/hellonico/origami-box

Closing, this one but looking forward to hear from your origami adventures.

By the way, if you have any idea about #1 ... let me know.
