### ISSUE TITLE
origami-dnn : provided draw/red-boxes goes out of bound

### ISSUE THREAD

**Issue by hellonico** [hellonico/origami#47]
```
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException
	at clojure.lang.RT.nthFrom(RT.java:924)
	at clojure.lang.RT.nth(RT.java:893)
	at origami_dnn.draw$red_boxes_BANG_.invokeStatic(draw.clj:20)
	at origami_dnn.draw$red_boxes_BANG_.invoke(draw.clj:16)
	at user$eval245$fn__246.invoke(dnn_from_folder.clj:21)
	at opencv4.utils$simple_cam_window$fn__192.invoke(utils.clj:353)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

and could be avoided.

**Comment by hellonico** [comment]
```
lein mobilenet.cam
```
works

**Comment by hellonico** [comment]
```
./dnn_from_folder.clj
```
works too.

Cannot reproduce
