### ISSUE TITLE
origami: aot use for filter.clj crashes clojure on some environment

### ISSUE THREAD

**Issue by hellonico** [hellonico/origami#51]
Caused by: java.lang.RuntimeException: Unable to resolve symbol: source in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7299)
	at clojure.lang.Compiler.resolve(Compiler.java:7243)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7204)
	at clojure.lang.Compiler.analyze(Compiler.java:6752)
	... 131 more

**Comment by hellonico** [comment]
ready to be released
