### ISSUE TITLE
Ver 4.5.1-0 to 4.5.1-7 on windows 10, Couldn't load library library opencv_java451 exception while compiling

### ISSUE THREAD

**Issue by imranypatel** [hellonico/origami#81]
Following Getting Started at https://cljdoc.org/d/origami/origami/4.1.2-7/doc/readme#getting-started

### install the sample
lein new clj-opencv hello-origami

### change directory
cd hello-origami

### run the template simple example
lein run

D:\Work\iprnd\clojure\hello-origami>lein run
Loading: opencv_java451
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(opencv4/ok.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.load(RT.java:460)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)....
    .....at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)....
... at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7051)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 40 more
Caused by: java.lang.RuntimeException: java.io.IOException: Couldn't load library library opencv_java451
        at origami.Origami.init(Origami.java:121)
        at opencv4.core__init.load(Unknown Source)
        at opencv4.core__init.<clinit>(Unknown Source)
        ... 71 more
Caused by: java.io.IOException: Couldn't load library library opencv_java451
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
        at origami.Origami.init(Origami.java:117)
        ... 73 more
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java451 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)
        ... 74 more

Experiencing same problem from 4.5.1-0 to 4.5.1-7.

Any advise please?

**Comment by hellonico** [comment]
I am back ! after two weeks and a knee surgery ...

**Comment by hellonico** [comment]
So, I have reinstalled windows10 here, and things are working fine here. 

![origami is ok](https://user-images.githubusercontent.com/10365/141104924-5eff87db-37d4-404f-867a-a623e4a88f0f.PNG)

This is on an 64 bit processor.
![set and processor](https://user-images.githubusercontent.com/10365/141104940-d84aebff-1d30-4d5c-92e5-bf05008aa679.PNG)

And java 17.

Could you open a command prompt and tell me the output of the command **set**

**Comment by imranypatel** [comment]
Hope you are doing well.
Picked it up again.
Just attempted afresh and it works!
Thank you.
